-- ============================================================
-- HOLLOW ATLAS — Add state column to locations
-- Run in: Supabase Dashboard → SQL Editor → New query
-- Must be run AFTER all seed files have been loaded.
-- Safe to re-run — all statements are idempotent.
-- TAS: 45 | NSW: 45 | VIC: 45 | QLD: 45 | SA: 45 | WA: 45 | NT: 45
-- ============================================================

ALTER TABLE public.locations
ADD COLUMN IF NOT EXISTS state text;

CREATE INDEX IF NOT EXISTS locations_state_idx ON public.locations (state);

-- ── Tasmania (45 locations: 30 original + 15 extra haunted/paranormal) ──────
UPDATE public.locations SET state = 'TAS' WHERE slug IN (
  'port-arthur-parsonage',
  'isle-of-the-dead',
  'willow-court-asylum',
  'richmond-bridge',
  'sarah-island',
  'hobart-convict-penitentiary',
  'anglesea-barracks-military-gaol',
  'cascades-female-factory',
  'franklin-house-launceston',
  'queenstown-lunar-landscape',
  'pillinger-ghost-town',
  'mathinna-gold-rush-town',
  'zeehan-gaiety-theatre',
  'oatlands-solomon-blay',
  'bridgewater-causeway',
  'maria-island-darlington',
  'maatsuyker-island-lighthouse',
  'campbell-street-gaol',
  'wybalenna-flinders-island',
  'oyster-cove-station',
  'arthur-river-thylacine-country',
  'bass-strait-valentich',
  'linda-ghost-town',
  'north-mount-lyell-disaster',
  'beaconsfield-gold-mine',
  'spray-silver-mine-ruins',
  'dundas-ghost-town',
  'recherche-bay',
  'williamsford-hercules-mine',
  'bradys-lookout-west-tamar',
  -- extra haunted/paranormal batch
  'theatre-royal-hobart',
  'richmond-gaol-1825',
  'coal-mines-saltwater-river',
  'st-davids-park-hobart',
  'lenna-hotel-hobart',
  'woolmers-estate-longford',
  'clarendon-house-evandale',
  'highfield-vdc-stanley',
  'eaglehawk-neck-dog-line',
  'bothwell-castle-hotel',
  'narryna-battery-point',
  'kunanyi-chalet-ruins',
  'weldborough-pub-ghost',
  'lake-st-clair-missing',
  'risdon-cove-1804'
);

-- ── New South Wales (45 locations: 30 original + 15 extra haunted/paranormal) ─
UPDATE public.locations SET state = 'NSW' WHERE slug IN (
  'monte-cristo-junee',
  'maitland-gaol',
  'berrima-gaol',
  'cockatoo-island',
  'old-government-house-parramatta',
  'trial-bay-gaol',
  'wentworth-gaol',
  'q-station-manly',
  'hawkesbury-river-monster',
  'min-min-lights-nsw',
  'yowie-blue-mountains',
  'newnes-ghost-town',
  'silverton-ghost-town',
  'yerranderie-silver-city',
  'hill-end',
  'kiandra',
  'old-adaminaby',
  'captains-flat',
  'hartley-historic-village',
  'gosford-glyphs',
  'lambing-flat-riots',
  'myall-creek-massacre',
  'norfolk-island-penal-colony',
  'dunbar-wreck',
  'battle-of-broken-hill',
  'castle-hill-rebellion',
  'waterloo-creek-massacre',
  'gundagai-flood-1852',
  'ben-halls-last-stand',
  'breelong-governor-rampage',
  -- extra haunted/paranormal batch
  'picton-mushroom-tunnel',
  'jenolan-caves-wiburd',
  'fisher-ghost-campbelltown',
  'hyde-park-barracks-ghosts',
  'wisemans-ferry-inn',
  'junee-roundhouse',
  'carcoar-nsw',
  'rookwood-necropolis',
  'gladesville-hospital-nsw',
  'armidale-saumarez-homestead',
  'kiama-lighthouse-1887',
  'st-albans-settlers-arms',
  'braidwood-nsw-colonial',
  'goulburn-historic-gaol',
  'newcastle-signal-station'
);

-- ── Victoria (45 locations: 30 original + 15 extra haunted/paranormal) ──────
UPDATE public.locations SET state = 'VIC' WHERE slug IN (
  'aradale-j-ward',
  'old-melbourne-gaol',
  'beechworth-lunatic-asylum',
  'pentridge-prison',
  'geelong-gaol',
  'cape-otway-lighthouse',
  'ballarat-gaol',
  'loch-ard-gorge',
  'hanging-rock',
  'lake-tyrrell',
  'bunyip-western-district',
  'bunjil-gariwerd',
  'walhalla',
  'steiglitz',
  'fryerstown',
  'tarnagulla',
  'blackwood-goldfields',
  'graytown',
  'yallourn',
  'kelly-last-stand-glenrowan',
  'eureka-stockade',
  'burke-and-wills-departure',
  'convincing-ground-massacre',
  'warrigal-creek-massacre',
  'murchison-pow-escape',
  'creswick-mine-disaster',
  'black-thursday-1851',
  'buckland-river-riot',
  'point-nepean',
  'phar-lap',
  -- extra haunted/paranormal batch
  'barwon-park-mansion',
  'daylesford-convent-gallery',
  'gippsland-haunted-hills',
  'maldon-kangaroo-hotel',
  'royal-hotel-seymour-vic',
  'tahbilk-winery-cellars',
  'dunolly-criterion-hotel',
  'werribee-mansion-ghost',
  'point-lonsdale-lighthouse',
  'mount-franklin-crater-vic',
  'sorrento-continental-hotel',
  'emu-bottom-homestead-sunbury',
  'benalla-hume-freeway-black-spot',
  'haunted-hills-hotel-drouin',
  'sunbury-vineyard-cemetery'
);

-- ── Queensland (45 locations: 30 original + 15 extra haunted/paranormal) ─────
UPDATE public.locations SET state = 'QLD' WHERE slug IN (
  'boggo-road-gaol',
  'wolston-park-hospital',
  'toowong-cemetery',
  'fernberg-government-house',
  'old-ipswich-gaol',
  'charters-towers-venus-battery',
  'min-min-lights-boulia',
  'tully-ufo-saucer-nest',
  'gundiah-mackay-abduction',
  'bunyip-lake-galilee',
  'gympie-pyramid',
  'ravenswood-ghost-town',
  'cracow-ghost-town',
  'mount-morgan-mine',
  'irvinebank-ghost-town',
  'chillagoe-smelter-ruins',
  'blackall-wool-scour',
  'tyrconnell-gold-mine',
  'einasleigh-ghost-town',
  'yongala-shipwreck-1911',
  'waltzing-matilda-winton',
  'lark-quarry-dinosaur-trackways',
  'kilcoy-massacre-1842',
  'cooktown-endeavour-river',
  'cloncurry-heat-record',
  'lamington-usaaf-crash-1943',
  'eliza-fraser-shipwreck',
  'longreach-qantas-birthplace',
  'birdsville-track-madigan',
  'stanthorpe-spanish-flu-border',
  -- extra haunted/paranormal batch
  'st-helena-island-qld',
  'nudgee-cemetery-brisbane',
  'goodna-cemetery-asylum',
  'childers-palace-fire-2000',
  'charters-towers-excelsior-hotel',
  'mount-coot-tha-ghost-hole',
  'barcaldine-tree-of-knowledge',
  'jondaryan-woolshed-qld',
  'magnetic-island-fort',
  'glasshouse-mountains-tibrogargan',
  'wolston-house-brisbane',
  'undara-lava-tubes',
  'ravenswood-cemetery-qld',
  'grange-homestead-brisbane',
  'innisfail-district-hospital'
);

-- ── South Australia (45 locations: 30 original + 15 extra haunted/paranormal) ─
UPDATE public.locations SET state = 'SA' WHERE slug IN (
  'adelaide-gaol',
  'magill-reformatory',
  'port-adelaide-hulks',
  'martindale-hall-mintaro',
  'burra-dugout-homes',
  'mount-gambier-cave-garden',
  'nullarbor-knowles-ufo-1988',
  'coorong-phantom-lights',
  'moonta-copper-triangle-apparitions',
  'bunyip-lake-alexandrina',
  'wilpena-pound-arkaroo',
  'kanyaka-station-ruins',
  'farina-ghost-town',
  'leigh-creek-old-township',
  'tailem-bend-ghost-town',
  'teetulpa-goldfield',
  'blinman-copper-mine',
  'port-willunga-jetty-ruins',
  'waukaringa-ghost-town',
  'somerton-man-1948',
  'maralinga-nuclear-tests',
  'hindmarsh-island-controversy',
  'coober-pedy-underground-city',
  'marree-man-geoglyph',
  'kapunda-vampire-grave',
  'morgan-chinese-massacre-1851',
  'kangaroo-island-sealers',
  'encounter-bay-whale-station',
  'snowtown-murders-1999',
  'glenelg-landing-1836',
  -- extra haunted/paranormal batch
  'adelaide-arcade-cluney',
  'north-kapunda-hotel',
  'carclew-house-north-adelaide',
  'seppeltsfield-winery-barossa',
  'burra-unicorn-brewery-cellars',
  'hahndorf-german-cemetery',
  'port-willunga-jetty-ghost',
  'morialta-gorge-spirits',
  'old-glenelg-hotel-ghost',
  'peterborough-steamtown-ghosts',
  'jamestown-historic-gaol',
  'victor-harbor-bluff-ghost',
  'wilpena-pound-arkaroo-rock',
  'auburn-sa-haunted-town',
  'hindmarsh-island-bridge-spirit'
);

-- ── Western Australia (45 locations: 30 original + 15 extra haunted/paranormal)
UPDATE public.locations SET state = 'WA' WHERE slug IN (
  'fremantle-prison',
  'fremantle-arts-centre-asylum',
  'the-round-house-fremantle',
  'york-residency-museum',
  'toodyay-convict-gaol',
  'wooroloo-hospital-ruins',
  'rottnest-island-apparitions',
  'nullarbor-wa-lights',
  'kimberley-wandjina-caves',
  'bunyip-swan-river',
  'yowie-darling-range',
  'wittenoom-blue-asbestos',
  'gwalia-ghost-town',
  'cossack-ghost-town',
  'yalgoo-ghost-town',
  'goldsworthy-abandoned-town',
  'ora-banda-ghost-town',
  'sandstone-ghost-town-wa',
  'meekatharra-goldfields',
  'batavia-shipwreck-1629',
  'rottnest-wadjemup-prison',
  'monte-bello-atomic-tests',
  'broome-flying-boats-1942',
  'jandamarra-bunuba-war',
  'kalgoorlie-1934-riots',
  'skylab-esperance-1979',
  'murujuga-petroglyphs',
  'noonkanbah-dispute-1980',
  'shark-bay-dampier-1688',
  'moore-river-stolen-generations',
  -- extra haunted/paranormal batch
  'ss-alkimos-wreck',
  'heathcote-hospital-wa',
  'fremantle-female-factory-wa',
  'new-norcia-monastery-wa',
  'kalgoorlie-golden-mile-ghost',
  'york-haunted-residency',
  'rottnest-quod-history',
  'mundaring-weir-engineer',
  'broome-japanese-cemetery-wa',
  'ora-banda-hotel-wa',
  'cossack-ghost-town-haunted',
  'fremantle-east-end-hospital',
  'guildford-grammar-wa',
  'hmas-sydney-memorial-geraldton',
  'kalgoorlie-hay-street-history'
);

-- ── Northern Territory (45 locations: 30 original + 15 extra haunted/paranormal)
UPDATE public.locations SET state = 'NT' WHERE slug IN (
  'fannie-bay-gaol',
  'darwin-bombed-nurses-quarters',
  'pine-creek-miners-cemetery',
  'larrimah-pub-disappearance',
  'mataranka-elsey-homestead',
  'victoria-settlement-cobourg',
  'wycliffe-well-ufo-capital',
  'henbury-meteorite-craters',
  'pine-gap-facility-lights',
  'mimih-spirits-arnhem-land',
  'rainbow-serpent-nitmiluk',
  'hatches-creek-wolfram',
  'tennant-creek-battery-hill',
  'newcastle-waters-drovers',
  'borroloola-old-courthouse',
  'umbrawarra-tin-mine',
  'connells-lagoon-ruins',
  'daly-waters-old-airstrip',
  'birdum-ghost-town',
  'darwin-bombing-1942',
  'cyclone-tracy-1974',
  'wave-hill-walkoff-1966',
  'milirrpum-gove-land-rights-1971',
  'azaria-chamberlain-1980',
  'coniston-massacre-1928',
  'lasseters-reef-legend',
  'kahlin-compound-darwin',
  'overland-telegraph-1872',
  'uluru-climb-closure',
  'stolen-children-retta-dixon',
  -- extra haunted/paranormal batch
  'poinciana-woman-east-point',
  'alice-springs-telegraph-station-ghost',
  'darwin-railway-station-ghosts',
  'roper-river-mission-nt',
  'victoria-hotel-darwin-ghost',
  'rum-jungle-uranium-mine',
  'elsey-station-cemetery-nt',
  'stuart-highway-ghost-km-202',
  'darwin-botanic-gardens-ghost',
  'litchfield-lost-city-spirits',
  'tennant-creek-police-ghost',
  'arnhem-land-escarpment-mimih',
  'pine-creek-gaol-haunted',
  'darwin-berrimah-prison-ghost',
  'nitmiluk-gorge-night-spirits'
);
